config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  get 'warehouse/index'

  get 'welcome/index'

  get 'warehouse/add_item', as: 'add_item'
  post 'warehouse/save_item', as: 'create_item'
  get 'warehouse/show_all', as: 'show_all_items'
  get 'warehouse/item_details/:id', to: 'warehouse#get_details', as: 'get_item'
  get 'warehouse/delete_item/:id', to: 'warehouse#delete_item', as: 'delete_item'
  patch 'warehouse/item_details/:id', to: 'warehouse#modify_item', as: 'modify_item'

  resources :categories

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, uniqueness: true
end

app/models/item.rb
class ItemValidator < ActiveModel::Validator
def validate(item)
  validate_datasheet(item)
end

  def validate_datasheet(item)
    datasheet = item.datasheet
    if datasheet.nil? || datasheet == "" || datasheet =~ URI::regexp
      return
    end
    item.errors[:datasheet] << "Datasheet should be a valid link or be empty"
  end
end

class Item < ApplicationRecord
  belongs_to :category, optional: true
  validates_with ItemValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @categories = @categories.sort_by{|category| category.items.count}.reverse_each
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category)
          .permit(:name)
    end

end

app/controllers/warehouse_controller.rb
class WarehouseController < ApplicationController
  def index
  end

  def add_item # view
    @item = Item.new
    @categories = Category.all
  end

  def get_details #view
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def save_item # action
    @item = Item.new(item_params)
    @categories = Category.all
    if @item.save
      redirect_to show_all_items_path
    else
      render :add_item
    end

  end

  def modify_item # action
    @item = Item.find(params[:id])
    @categories = Category.all
    if @item.update(item_params)
      redirect_to show_all_items_path
    else
      render :get_details
    end
  end

  def delete_item # action
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to show_all_items_path
  end

  def show_all # view
    @all_items = Item.all
  end

private
def item_params
  params.require(:item)
        .permit(:name, :producent, :datasheet, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/warehouse_helper.rb
module WarehouseHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for category, :html => {:class => 'form-inline'} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => 'Category name', :class => 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
<% end %>
<% if category.errors.any? %>
  <div class="alert alert-danger">
    Category already exists.
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="container">
  <%= link_to 'Add new category', new_category_path, :class=>"btn btn-primary" %>
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @categories.each do |category| %>
      <td><%= category.name %></td>
      <td><%= category.items.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/layouts/_header_template.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to 'Warehouse', show_all_items_path %>
      </li>
      <li>
        <%= link_to 'Categories', categories_index_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header_template' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/warehouse/_file_form.html.erb
<%= form_for item, url: action_url, :html => {:class => 'form-inline'} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :producent %>
    <%= f.text_field :producent, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :datasheet, 'Datasheet (URL)' %>
    <%= f.text_field :datasheet, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, categories, :id, :name, {}, {:class => 'form-control'} %>
  </div>
  <%= f.submit :class => 'btn btn-primary' %>
  <% if item.errors.any? %>
    <div class="alert alert-danger">
      Incorrect input.
    </div>
  <% end %>
<% end %>

app/views/warehouse/add_item.html.erb
<%= render 'file_form', item: @item, categories: @categories, action_url: create_item_path %>

app/views/warehouse/get_details.html.erb
<p id="notice"><%= notice %></p>
<%= render 'file_form', item: @item, categories: @categories, action_url: modify_item_path%>
</br>
<%= link_to 'Delete', delete_item_path(@item), :class=>"btn btn-danger"%>

app/views/warehouse/index.html.erb
<%= link_to 'Show all items', show_all_items_path, :class=>"btn btn-primary"%>
<%= link_to 'Add new item', add_item_path, :class=>"btn btn-primary" %>

app/views/warehouse/show_all.html.erb
<div class="container">
  <%= link_to 'Add new item', add_item_path, :class=>"btn btn-primary" %>
  <table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Producent</th>
      <th>Datasheet</th>
      <th>Category</th>
      <th>Details</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @all_items.each do |item| %>
      <td><%= item.id %></td>
      <td><%= item.name %></td>
      <td><%= item.producent %></td>
      <% if URI::regexp.match(item.datasheet) %>
      <td><a href="<%= item.datasheet%>" target="_blank">Link</a></td>
      <% else %>
      <td><%= item.datasheet %></td>
      <% end %>

      <td><%= item.category.name unless item.category.nil? %></td>
      <td><%= link_to 'Show details', get_item_path(item), :class=>"btn btn-info"%></td>
      <td><%= link_to 'Delete', delete_item_path(item), :class=>"btn btn-danger"%></td>
    </tr>
    <% end %>
  </tbody>

</table>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>